### ISSUE TITLE
Incompatibility with Hydrogen mod

### ISSUE THREAD

**Issue by Pairman** [alphaqu/DashLoader-Legacy#34]
Hydrogen: https://github.com/CaffeineMC/hydrogen-fabric
Dashloader and hydrogen conflict with each other

**Comment by pluiedev** [comment]
This is a known issue, and [has been marked so deliberately](https://github.com/alphaqu/DashLoader/blob/8ae774e7a836dc91d69044f0d60c16083998f72f/src/main/resources/fabric.mod.json#L41). @alphaqu do NOT close this, since we don't need more people flooding in asking why Hydrogen, EBE, etc. don't work with Dash

**Comment by Pairman** [comment]
> This is a known issue, and [has been marked so deliberately](https://github.com/alphaqu/DashLoader/blob/8ae774e7a836dc91d69044f0d60c16083998f72f/src/main/resources/fabric.mod.json#L41). @alphaqu do NOT close this, since we don't need more people flooding in asking why Hydrogen, EBE, etc. don't work with Dash

Sorry for my not looking into the closed ones. Tnaks for answering

**Comment by alphaqu** [comment]
We have fancy list now.
